version: "3.7"
services:
  primary:
    image: powerdns/pdns-auth-46:latest
    ports:
      - 127.0.0.1:5301:53/udp
      - 127.0.0.1:5301:53/tcp
    expose:
      - 53
    volumes:
      - ./primary/pdns.conf:/etc/powerdns/pdns.conf
      - ./primary/lmdb/:/var/lib/pdns/
  secondary:
    image: powerdns/pdns-auth-46:latest
    ports:
      - 127.0.0.1:5302:53/udp
      - 127.0.0.1:5302:53/tcp
    expose:
      - 53
    volumes:
      - ./secondary/pdns.conf:/etc/powerdns/pdns.conf
      - ./secondary/lmdb/:/var/lib/pdns/


